//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTestApplication.InterestRateCalcService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SebCustomer", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class SebCustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalId {
            get {
                return this.PersonalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalIdField, value) != true)) {
                    this.PersonalIdField = value;
                    this.RaisePropertyChanged("PersonalId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterestRateCalcService.IInterestRateCalcService")]
    public interface IInterestRateCalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateCalcService/ItWorks", ReplyAction="http://tempuri.org/IInterestRateCalcService/ItWorksResponse")]
        string ItWorks(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateCalcService/ItWorks", ReplyAction="http://tempuri.org/IInterestRateCalcService/ItWorksResponse")]
        System.Threading.Tasks.Task<string> ItWorksAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateCalcService/GetCustomer", ReplyAction="http://tempuri.org/IInterestRateCalcService/GetCustomerResponse")]
        WcfServiceTestApplication.InterestRateCalcService.SebCustomer GetCustomer(string personalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateCalcService/GetCustomer", ReplyAction="http://tempuri.org/IInterestRateCalcService/GetCustomerResponse")]
        System.Threading.Tasks.Task<WcfServiceTestApplication.InterestRateCalcService.SebCustomer> GetCustomerAsync(string personalId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterestRateCalcServiceChannel : WcfServiceTestApplication.InterestRateCalcService.IInterestRateCalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterestRateCalcServiceClient : System.ServiceModel.ClientBase<WcfServiceTestApplication.InterestRateCalcService.IInterestRateCalcService>, WcfServiceTestApplication.InterestRateCalcService.IInterestRateCalcService {
        
        public InterestRateCalcServiceClient() {
        }
        
        public InterestRateCalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterestRateCalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterestRateCalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterestRateCalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ItWorks(int a) {
            return base.Channel.ItWorks(a);
        }
        
        public System.Threading.Tasks.Task<string> ItWorksAsync(int a) {
            return base.Channel.ItWorksAsync(a);
        }
        
        public WcfServiceTestApplication.InterestRateCalcService.SebCustomer GetCustomer(string personalId) {
            return base.Channel.GetCustomer(personalId);
        }
        
        public System.Threading.Tasks.Task<WcfServiceTestApplication.InterestRateCalcService.SebCustomer> GetCustomerAsync(string personalId) {
            return base.Channel.GetCustomerAsync(personalId);
        }
    }
}
